services:
  - type: web
    name: nmits
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: nmits_db
      - key: FLASK_ENV
        value: production
